export const BLOG_KEYWORDS = [
  "LinkedIn for real estate agents Australia",
  "how to do personal branding on LinkedIn",
  "how to grow on LinkedIn 2026",
  "LinkedIn tips for real estate agents Australia",
  "personal branding Sydney",
  "how to grow LinkedIn following",
  "why personal branding matters",
  "personal branding Melbourne",
  "how to grow on LinkedIn as a business",
  "how to start personal branding",
  "LinkedIn for small business Australia",
  "personal branding Perth",
  "how to grow quickly on LinkedIn",
  "benefits of personal brand marketing",
  "LinkedIn content ideas Australia",
  "what is personal branding on LinkedIn",
  "how to grow on LinkedIn as a creator",
  "how to improve personal branding",
  "LinkedIn profile tips Australia",
  "personal branding strategy",
  "LinkedIn for tradies Australia",
  "how much does personal branding cost",
  "how to build personal branding on social media",
] as const;
