export const BLOG_KEYWORDS = [
  "LinkedIn ghostwriting Australia",
  "what is LinkedIn ghostwriting",
  "benefits of LinkedIn ghostwriting",
  "hire a LinkedIn ghostwriter",
  "LinkedIn ghostwriter for small business",
  "LinkedIn ghostwriting service Australia",
  "is LinkedIn ghostwriting ethical",
  "how much does LinkedIn ghostwriting cost",
  "LinkedIn ghostwriter for real estate agents",
  "LinkedIn ghostwriter for business owners",
  "LinkedIn for real estate agents Australia",
  "how to do personal branding on LinkedIn",
  "how to grow on LinkedIn 2026",
  "LinkedIn tips for real estate agents",
  "personal branding Sydney",
  "how to grow LinkedIn following",
  "why personal branding matters",
  "personal branding Melbourne",
  "how to grow on LinkedIn as a business",
  "how to start personal branding",
  "LinkedIn for small business",
  "personal branding Perth",
  "how to grow quickly on LinkedIn",
  "benefits of personal brand marketing",
  "LinkedIn content ideas",
  "what is personal branding on LinkedIn",
  "how to grow on LinkedIn as a creator",
  "how to improve personal branding",
  "LinkedIn profile tips",
  "personal branding strategy",
  "LinkedIn for tradies",
  "how much does personal branding cost",
  "how to build personal branding on social media",
  "LinkedIn content strategy for business owners",
  "why you should post on LinkedIn",
  "how to get leads on LinkedIn",
  "LinkedIn for mortgage brokers",
  "LinkedIn for financial advisers",
  "LinkedIn personal brand tips",
  "how to build authority on LinkedIn",
] as const;
