export const BLOG_KEYWORDS = [
  "LinkedIn ghostwriting",
  "LinkedIn ghostwriting service",
  "LinkedIn ghostwriter for hire",
  "professional LinkedIn ghostwriter",
  "best LinkedIn ghostwriting service 2026",
  "LinkedIn ghostwriting for entrepreneurs",
  "LinkedIn ghostwriting for executives",
  "LinkedIn ghostwriting for coaches",
  "LinkedIn ghostwriting for consultants",
  "LinkedIn ghostwriting for personal brand",
  "LinkedIn ghostwriting pricing",
  "LinkedIn ghostwriting cost",
  "how much does a LinkedIn ghostwriter cost",
  "how to hire a LinkedIn ghostwriter",
  "is LinkedIn ghostwriting worth it",
  "LinkedIn ghostwriting vs doing it yourself",
  "what is LinkedIn ghostwriting",
  "benefits of LinkedIn ghostwriting",
  "is LinkedIn ghostwriting ethical",
  "LinkedIn ghostwriting Australia",
  "LinkedIn ghostwriter Australia",
  "LinkedIn ghostwriting service Australia",
  "LinkedIn ghostwriter for real estate agents",
  "LinkedIn ghostwriter for mortgage brokers",
  "LinkedIn ghostwriter for financial advisers",
  "LinkedIn ghostwriter for small business",
  "LinkedIn ghostwriter for business owners",
  "LinkedIn for real estate agents Australia",
  "LinkedIn for mortgage brokers Australia",
  "LinkedIn for financial advisers Australia",
  "LinkedIn for tradies Australia",
  "done for you LinkedIn content",
  "outsource LinkedIn content",
  "outsource LinkedIn posts",
  "LinkedIn content writing service",
  "LinkedIn post writing service",
  "LinkedIn writing service for business",
  "LinkedIn content outsourcing",
  "LinkedIn personal branding tips",
  "how to do personal branding on LinkedIn",
  "LinkedIn personal brand tips",
  "how to grow on LinkedIn 2026",
  "LinkedIn tips for business owners",
  "LinkedIn content ideas for professionals",
  "LinkedIn content strategy for business owners",
  "LinkedIn lead generation for business owners",
  "how to get clients on LinkedIn",
  "how to build authority on LinkedIn",
  "how to post consistently on LinkedIn",
  "why you should post on LinkedIn",
  "LinkedIn profile tips",
  "LinkedIn for small business",
  "personal branding strategy",
  "personal branding Sydney",
  "personal branding Melbourne",
  "personal branding Perth",
] as const;
