export const PILLAR_KEYWORDS = [
  "what is LinkedIn ghostwriting and is it worth it",
  "how to hire a LinkedIn ghostwriter",
  "best LinkedIn ghostwriting services 2026",
  "LinkedIn ghostwriting vs doing it yourself",
  "how much does LinkedIn ghostwriting cost",
  "LinkedIn ghostwriting for executives complete guide",
  "LinkedIn ghostwriting for coaches and consultants",
  "LinkedIn ghostwriting for financial professionals",
  "LinkedIn ghostwriting for real estate professionals",
  "how to find a LinkedIn ghostwriter",
  "is LinkedIn ghostwriting ethical",
  "LinkedIn ghostwriting service for entrepreneurs",
  "how to get clients on LinkedIn",
  "what to post on LinkedIn as a business owner",
  "LinkedIn personal branding for professionals",
  "LinkedIn content strategy for small business",
  "how to grow on LinkedIn 2026",
  "LinkedIn ghostwriting Australia",
  "done for you LinkedIn content Australia",
  "how to build authority on LinkedIn",
  "LinkedIn tips for financial advisers",
  "LinkedIn profile tips for business owners",
  "how to post consistently on LinkedIn",
  "LinkedIn lead generation for business owners",
  "LinkedIn content ideas for professionals",
  "how to write LinkedIn posts that get engagement",
  "LinkedIn strategy for coaches and consultants",
  "LinkedIn for real estate agents Australia",
  "LinkedIn for mortgage brokers Australia",
  "how to get clients on LinkedIn Australia",
  "LinkedIn personal branding for Australian professionals",
  "LinkedIn content strategy for small business Australia",
  "LinkedIn ghostwriting service",
  "outsource LinkedIn content",
  "LinkedIn writing service",
  "LinkedIn for tradies Australia",
  "how to get referrals from LinkedIn",
  "LinkedIn lead generation guide",
  "LinkedIn personal branding complete guide",
  "LinkedIn content strategy guide 2026",
] as const;
