export const PILLAR_KEYWORDS = [
  "how to get clients on LinkedIn Australia",
  "what to post on LinkedIn as a business owner Australia",
  "LinkedIn personal branding for Australian professionals",
  "LinkedIn content strategy for small business Australia",
  "how to grow on LinkedIn Australia 2026",
  "LinkedIn for real estate agents Australia",
  "LinkedIn for mortgage brokers Australia",
  "LinkedIn ghostwriting Australia",
  "done for you LinkedIn content Australia",
  "how to build authority on LinkedIn Australia",
  "LinkedIn tips for financial advisers Australia",
  "LinkedIn profile tips for business owners Australia",
  "how to post consistently on LinkedIn Australia",
  "LinkedIn lead generation for Australian business owners",
  "personal branding on LinkedIn Australia guide",
  "LinkedIn content ideas for Australian professionals",
  "how to write LinkedIn posts that get engagement Australia",
  "LinkedIn strategy for coaches and consultants Australia",
  "LinkedIn for tradies Australia",
  "how to get referrals from LinkedIn Australia",
];
